export const PORTAGE_LIST = [
  {
    id: 1,
    nome: 'Observa uma pessoa movimentando-se em seu campo visual',
    faixaEtaria: '0 a 1',
    portage: 'Socialização',
  },
  {
    id: 2,
    nome: 'Sorri em resposta à atenção do adulto',
    faixaEtaria: '0 a 1',
    portage: 'Socialização',
  },
  {
    id: 3,
    nome: 'Vocaliza em resposta à atenção',
    faixaEtaria: '0 a 1',
    portage: 'Socialização',
  },
  {
    id: 4,
    nome: 'Olha para sua própria mão, sorrindo, vocalizando ou parando de chorar',
    faixaEtaria: '0 a 1',
    portage: 'Socialização',
  },
  {
    id: 5,
    nome: 'Responde a seu círculo familiar, sorrindo, vocalizando ou parando de chorar',
    faixaEtaria: '0 a 1',
    portage: 'Socialização',
  },
  {
    id: 6,
    nome: 'Sorri em resposta à expressão dos outros',
    faixaEtaria: '0 a 1',
    portage: 'Socialização',
  },
  {
    id: 7,
    nome: 'Sorri e vocaliza ao ver sua imagem no espelho',
    faixaEtaria: '0 a 1',
    portage: 'Socialização',
  },
  {
    id: 8,
    nome: 'Acaricia ou toca no rosto de adultos (puxa cabelo, nariz, óculos, etc)',
    faixaEtaria: '0 a 1',
    portage: 'Socialização',
  },
  {
    id: 9,
    nome: 'Estende a mão em direção a um objeto oferecido',
    faixaEtaria: '0 a 1',
    portage: 'Socialização',
  },
  {
    id: 10,
    nome: 'Estende os braços em direção a pessoas familiares',
    faixaEtaria: '0 a 1',
    portage: 'Socialização',
  },
  {
    id: 11,
    nome: 'Estende a mão e toca sua imagem refletida no espelho',
    faixaEtaria: '0 a 1',
    portage: 'Socialização',
  },
  {
    id: 12,
    nome: 'Segura e examina por 1 minuto um objeto que lhe foi dado',
    faixaEtaria: '0 a 1',
    portage: 'Socialização',
  },
  {
    id: 13,
    nome: 'Sacode um aperta um objeto colocado em sua mão, produzindo sons involuntários',
    faixaEtaria: '0 a 1',
    portage: 'Socialização',
  },
  {
    id: 14,
    nome: 'Brinca sozinho por 10 minutos',
    faixaEtaria: '0 a 1',
    portage: 'Socialização',
  },
  {
    id: 15,
    nome: 'Procura contato visual quando alguém lhe dá atenção por 2 a 3 minutos',
    faixaEtaria: '0 a 1',
    portage: 'Socialização',
  },
  {
    id: 16,
    nome: 'Brinca sozinho sem reclamar por 15 a 20 minutos, próximo de um adulto',
    faixaEtaria: '0 a 1',
    portage: 'Socialização',
  },
  {
    id: 17,
    nome: 'Vocaliza para obter atenção',
    faixaEtaria: '0 a 1',
    portage: 'Socialização',
  },
  {
    id: 18,
    nome: 'Imita adulto em brincadeiras de esconde-esconde',
    faixaEtaria: '0 a 1',
    portage: 'Socialização',
  },
  {
    id: 19,
    nome: 'Bate almas, imitando um adulto',
    faixaEtaria: '0 a 1',
    portage: 'Socialização',
  },
  {
    id: 20,
    nome: 'Acena a mão, imitando um adulto',
    faixaEtaria: '0 a 1',
    portage: 'Socialização',
  },
  {
    id: 21,
    nome: 'Ergue os braços para expressar “grande”, imitando um adulto',
    faixaEtaria: '0 a 1',
    portage: 'Socialização',
  },
  {
    id: 22,
    nome: ' Oferece algo, mas nem sempre entrega',
    faixaEtaria: '0 a 1',
    portage: 'Socialização',
  },
  {
    id: 23,
    nome: 'Abraça, acaricia e beija familiares',
    faixaEtaria: '0 a 1',
    portage: 'Socialização',
  },
  {
    id: 24,
    nome: 'Responde ao próprio nome, olhando ou estendendo o  braço para ser pego',
    faixaEtaria: '0 a 1',
    portage: 'Socialização',
  },
  {
    id: 25,
    nome: 'Aperta ou sacode um brinquedo para produzir sons, em imitação',
    faixaEtaria: '0 a 1',
    portage: 'Socialização',
  },
  {
    id: 26,
    nome: 'Manipula brinquedo ou objeto',
    faixaEtaria: '0 a 1',
    portage: 'Socialização',
  },
  {
    id: 27,
    nome: 'Estende um brinquedo ou objeto a um adulto e o entrega',
    faixaEtaria: '0 a 1',
    portage: 'Socialização',
  },
  {
    id: 28,
    nome: 'Imita movimentos de outras crianças ao brincar',
    faixaEtaria: '0 a 1',
    portage: 'Socialização',
  },
  {
    id: 29,
    nome: 'Imita um adulto em uma tarefa simples',
    faixaEtaria: '1 a 2',
    portage: 'Socialização',
  },
  {
    id: 30,
    nome: 'Brinca ao lado de outra criança, cada uma realizando tarefas diferentes',
    faixaEtaria: '1 a 2',
    portage: 'Socialização',
  },
  {
    id: 31,
    nome: 'Toma parte em uma brincadeira com outra criança por  2 a 5 minutos',
    faixaEtaria: '1 a 2',
    portage: 'Socialização',
  },
  {
    id: 32,
    nome: ' Aceita a ausência dos pais, embora possa reclamar',
    faixaEtaria: '1 a 2',
    portage: 'Socialização',
  },
  {
    id: 33,
    nome: ' Explora ativamente seu meio ambiente',
    faixaEtaria: '1 a 2',
    portage: 'Socialização',
  },
  {
    id: 34,
    nome: ' Realiza atividade manipulativa com outra pessoa',
    faixaEtaria: '1 a 2',
    portage: 'Socialização',
  },
  {
    id: 35,
    nome: 'Abraça e carrega uma boneca ou brinquedo macio',
    faixaEtaria: '1 a 2',
    portage: 'Socialização',
  },
  {
    id: 36,
    nome: 'Repete ações que produzem risos e atenção',
    faixaEtaria: '1 a 2',
    portage: 'Socialização',
  },
  {
    id: 37,
    nome: 'Dá um livro para que um adulto o leia ou para que ambos o compartilhem',
    faixaEtaria: '1 a 2',
    portage: 'Socialização',
  },
  {
    id: 38,
    nome: 'Puxa uma pessoa para a mostrar-lhe algo',
    faixaEtaria: '1 a 2',
    portage: 'Socialização',
  },
  {
    id: 39,
    nome: "Retira a mão ou diz 'não' quando está próximo de um objeto não permitido e alguém o lembra disto",
    faixaEtaria: '1 a 2',
    portage: 'Socialização',
  },
  {
    id: 40,
    nome: 'Quando colocado em sua cadeira ou trocador espera ser atendido',
    faixaEtaria: '1 a 2',
    portage: 'Socialização',
  },
  {
    id: 41,
    nome: 'Brinca com 2 ou 3 crianças de sua idade',
    faixaEtaria: '1 a 2',
    portage: 'Socialização',
  },
  {
    id: 42,
    nome: 'Compartilha um objeto ou alimento com outra criança',
    faixaEtaria: '1 a 2',
    portage: 'Socialização',
  },
  {
    id: 43,
    nome: 'Cumprimenta colegas ou adultos quando lembrado',
    faixaEtaria: '1 a 2',
    portage: 'Socialização',
  },
  {
    id: 44,
    nome: 'Obedece às ordens dos pais pelo menos ½ das vezes',
    faixaEtaria: '2 a 3',
    portage: 'Socialização',
  },
  {
    id: 45,
    nome: 'Busca/leva um objeto ou pessoa, quando solicitado',
    faixaEtaria: '2 a 3',
    portage: 'Socialização',
  },
  {
    id: 46,
    nome: 'Presta atenção à estória ou música por 5 a 10 minutos',
    faixaEtaria: '2 a 3',
    portage: 'Socialização',
  },
  {
    id: 47,
    nome: "Diz 'Por favor' ou 'Obrigado' quando lembrado",
    faixaEtaria: '2 a 3',
    portage: 'Socialização',
  },
  {
    id: 48,
    nome: 'Tenta ajudar os pais a executarem tarefas realizando parte da mesma',
    faixaEtaria: '2 a 3',
    portage: 'Socialização',
  },
  {
    id: 49,
    nome: 'Brinca de usar roupas de adultos',
    faixaEtaria: '2 a 3',
    portage: 'Socialização',
  },
  {
    id: 50,
    nome: 'Faz uma escolha quando indagado',
    faixaEtaria: '2 a 3',
    portage: 'Socialização',
  },
  {
    id: 51,
    nome: 'Demostra entender sentimentos, expressando-os',
    faixaEtaria: '2 a 3',
    portage: 'Socialização',
  },
  {
    id: 52,
    nome: 'Canta e dança ao ouvir músicas',
    faixaEtaria: '3 a 4',
    portage: 'Socialização',
  },
  {
    id: 53,
    nome: 'Segue regras de um jogo imitando ações de outras crianças',
    faixaEtaria: '3 a 4',
    portage: 'Socialização',
  },
  {
    id: 54,
    nome: 'Cumprimenta pessoas familiares sem ser lembrado',
    faixaEtaria: '3 a 4',
    portage: 'Socialização',
  },
  {
    id: 55,
    nome: 'Seguem regras em jogo de grupos dirigidos por adultos',
    faixaEtaria: '3 a 4',
    portage: 'Socialização',
  },
  {
    id: 56,
    nome: 'Pede permissão para brincar com um brinquedo que está sendo usado por outra criança',
    faixaEtaria: '3 a 4',
    portage: 'Socialização',
  },
  {
    id: 57,
    nome: "Diz 'Por favor' e 'Obrigado' sem ser lembrado ½ das vezes",
    faixaEtaria: '3 a 4',
    portage: 'Socialização',
  },
  {
    id: 58,
    nome: 'Atende ao telefone, chamando um adulto e falando com pessoas familiares',
    faixaEtaria: '3 a 4',
    portage: 'Socialização',
  },
  {
    id: 59,
    nome: 'Espera sua vez',
    faixaEtaria: '3 a 4',
    portage: 'Socialização',
  },
  {
    id: 60,
    nome: 'Segue regras em jogos dirigidos por uma criança mais velha',
    faixaEtaria: '3 a 4',
    portage: 'Socialização',
  },
  {
    id: 61,
    nome: 'Obedece às ordens de um adulto 75% das vezes. (3 vezes a cada 4 tentativas)',
    faixaEtaria: '3 a 4',
    portage: 'Socialização',
  },
  {
    id: 62,
    nome: ' Permanece em seu próprio quintal ou jardim',
    faixaEtaria: '3 a 4',
    portage: 'Socialização',
  },
  {
    id: 63,
    nome: 'Brinca perto de outras crianças conversando com elas enquanto trabalha em um projeto próprio (30 minutos)',
    faixaEtaria: '3 a 4',
    portage: 'Socialização',
  },
  {
    id: 64,
    nome: 'Pede ajuda quando esta tendo dificuldades',
    faixaEtaria: '4 a 5',
    portage: 'Socialização',
  },
  {
    id: 65,
    nome: 'Contribui para conversa de adultos',
    faixaEtaria: '4 a 5',
    portage: 'Socialização',
  },
  {
    id: 66,
    nome: 'Repete rimas, canções ou dança para os outros',
    faixaEtaria: '4 a 5',
    portage: 'Socialização',
  },
  {
    id: 67,
    nome: 'Faz uma tarefa sozinha por 20 a 30 minutos',
    faixaEtaria: '4 a 5',
    portage: 'Socialização',
  },
  {
    id: 68,
    nome: 'Pede desculpas sem ser lembrado 75% das vezes',
    faixaEtaria: '4 a 5',
    portage: 'Socialização',
  },
  {
    id: 69,
    nome: 'Espera sua vez em brincadeiras que envolvam de 8 a 9 crianças',
    faixaEtaria: '4 a 5',
    portage: 'Socialização',
  },
  {
    id: 70,
    nome: 'Brinca com 2 a 3 crianças por 20 minutos em uma atividades que envolva cooperação',
    faixaEtaria: '4 a 5',
    portage: 'Socialização',
  },
  {
    id: 71,
    nome: 'Quando em público, apresenta um comportamento socialmente aceitável',
    faixaEtaria: '4 a 5',
    portage: 'Socialização',
  },
  {
    id: 72,
    nome: 'Pede permissão para usar objeto dos outros em 75% das vezes',
    faixaEtaria: '4 a 5',
    portage: 'Socialização',
  },
  {
    id: 73,
    nome: 'Manifesta seus sentimentos',
    faixaEtaria: '5 a 6',
    portage: 'Socialização',
  },
  {
    id: 74,
    nome: 'Brinca com a criança em atividades de cooperação por 20 minutos, sem supervisão',
    faixaEtaria: '5 a 6',
    portage: 'Socialização',
  },
  {
    id: 75,
    nome: 'Explica aos outros as regras do jogo ou atividades',
    faixaEtaria: '5 a 6',
    portage: 'Socialização',
  },
  {
    id: 76,
    nome: 'Imita papéis de adulto',
    faixaEtaria: '5 a 6',
    portage: 'Socialização',
  },
  {
    id: 77,
    nome: 'Colabora para a conversa durante as refeições',
    faixaEtaria: '5 a 6',
    portage: 'Socialização',
  },
  {
    id: 78,
    nome: 'Segue regras de jogo que envolva raciocínio verbal',
    faixaEtaria: '5 a 6',
    portage: 'Socialização',
  },
  {
    id: 79,
    nome: 'Conforta colegas quando estes estão tristes',
    faixaEtaria: '5 a 6',
    portage: 'Socialização',
  },
  {
    id: 80,
    nome: 'Escolhe seus próprios amigos',
    faixaEtaria: '5 a 6',
    portage: 'Socialização',
  },
  {
    id: 81,
    nome: 'Planeja e constrói, usando ferramentas simples',
    faixaEtaria: '5 a 6',
    portage: 'Socialização',
  },
  {
    id: 82,
    nome: 'Estabelece metas para si próprio e executa atividades para atingi-las',
    faixaEtaria: '5 a 6',
    portage: 'Socialização',
  },
  {
    id: 83,
    nome: 'Dramatiza trechos de histórias, desempenhando um papel ou utilizando fantoches',
    faixaEtaria: '5 a 6',
    portage: 'Socialização',
  },
  {
    id: 1,
    nome: 'Remove um pano do rosto obscureça sua visão',
    faixaEtaria: '0 a 1',
    portage: 'Cognição',
  },
  {
    id: 2,
    nome: 'Procura com olhar um objeto que foi tirado de seu campo visual',
    faixaEtaria: '0 a 1',
    portage: 'Cognição',
  },
  {
    id: 3,
    nome: 'Remove um objeto de um recipiente colocando a mão dentro do mesmo',
    faixaEtaria: '0 a 1',
    portage: 'Cognição',
  },
  {
    id: 4,
    nome: 'Coloca um objeto em um recipiente imitando um adulto',
    faixaEtaria: '0 a 1',
    portage: 'Cognição',
  },
  {
    id: 5,
    nome: 'Coloca um objeto em um recipiente quando recebe instruções',
    faixaEtaria: '0 a 1',
    portage: 'Cognição',
  },
  {
    id: 6,
    nome: 'Balança um brinquedo que produz som, pendurado em um barbante',
    faixaEtaria: '0 a 1',
    portage: 'Cognição',
  },
  {
    id: 7,
    nome: 'Coloca três objetos em um recipiente e o esvazia',
    faixaEtaria: '0 a 1',
    portage: 'Cognição',
  },
  {
    id: 8,
    nome: 'Transfere um objeto de uma mão à outra para apanhar outro objeto',
    faixaEtaria: '0 a 1',
    portage: 'Cognição',
  },
  {
    id: 9,
    nome: ' Deixa cair e apanha um brinquedo',
    faixaEtaria: '0 a 1',
    portage: 'Cognição',
  },
  {
    id: 10,
    nome: 'Descobre um objeto escondido sob um recipiente',
    faixaEtaria: '0 a 1',
    portage: 'Cognição',
  },
  {
    id: 11,
    nome: 'Empurra 3 blocos como se fosse um comboio',
    faixaEtaria: '0 a 1',
    portage: 'Cognição',
  },
  {
    id: 12,
    nome: 'Remove um círculo de uma prancha, por imitação',
    faixaEtaria: '0 a 1',
    portage: 'Cognição',
  },
  {
    id: 13,
    nome: 'Coloca um pino redondo em uma prancha de pinos, quando solicitado',
    faixaEtaria: '0 a 1',
    portage: 'Cognição',
  },
  {
    id: 14,
    nome: 'Executa gestos simples quando requisitado',
    faixaEtaria: '0 a 1',
    portage: 'Cognição',
  },
  {
    id: 15,
    nome: 'Retira 6 objetos de um recipiente, um por vez',
    faixaEtaria: '1 a 2',
    portage: 'Cognição',
  },
  {
    id: 16,
    nome: 'Aponta para uma parte do corpo',
    faixaEtaria: '1 a 2',
    portage: 'Cognição',
  },
  {
    id: 17,
    nome: 'Empilha 3 blocos, dada a ordem',
    faixaEtaria: '1 a 2',
    portage: 'Cognição',
  },
  {
    id: 18,
    nome: 'Emparelha objetos semelhantes',
    faixaEtaria: '1 a 2',
    portage: 'Cognição',
  },
  {
    id: 19,
    nome: 'Faz rabiscos no papel',
    faixaEtaria: '1 a 2',
    portage: 'Cognição',
  },
  {
    id: 20,
    nome: "Aponta para sim quando perguntam 'Cadê o fulano?'",
    faixaEtaria: '1 a 2',
    portage: 'Cognição',
  },
  {
    id: 21,
    nome: 'Coloca 5 pinos redondos, dada a ordem',
    faixaEtaria: '1 a 2',
    portage: 'Cognição',
  },
  {
    id: 22,
    nome: 'Emparelha objetos com a figura do mesmo nome',
    faixaEtaria: '1 a 2',
    portage: 'Cognição',
  },
  {
    id: 23,
    nome: 'Aponta para afigura nomeada',
    faixaEtaria: '1 a 2',
    portage: 'Cognição',
  },
  {
    id: 24,
    nome: 'Viras as páginas de um livro (2/3 por vez) para encontrar a figura nomeada',
    faixaEtaria: '1 a 2',
    portage: 'Cognição',
  },
  {
    id: 25,
    nome: 'Encontra determinado livro quando solicitado',
    faixaEtaria: '2 a 3',
    portage: 'Cognição',
  },
  {
    id: 26,
    nome: 'Completa um quebra-cabeça de encaixe de 3 peças',
    faixaEtaria: '2 a 3',
    portage: 'Cognição',
  },
  {
    id: 27,
    nome: 'Nomeia 4 objetos comuns em figuras',
    faixaEtaria: '2 a 3',
    portage: 'Cognição',
  },
  {
    id: 28,
    nome: 'Desenha uma linha vertical  imitando um adulto',
    faixaEtaria: '2 a 3',
    portage: 'Cognição',
  },
  {
    id: 29,
    nome: 'Desenha uma linha horizontal imitando um adulto',
    faixaEtaria: '2 a 3',
    portage: 'Cognição',
  },
  {
    id: 30,
    nome: 'Copia um círculo',
    faixaEtaria: '2 a 3',
    portage: 'Cognição',
  },
  {
    id: 31,
    nome: 'Emparelha objetos com a mesma textura',
    faixaEtaria: '2 a 3',
    portage: 'Cognição',
  },
  {
    id: 32,
    nome: "Aponta o 'pequeno' e o 'grande' quando solicitado",
    faixaEtaria: '2 a 3',
    portage: 'Cognição',
  },
  {
    id: 33,
    nome: 'Desenha (+) imitando um adulto..',
    faixaEtaria: '2 a 3',
    portage: 'Cognição',
  },
  {
    id: 34,
    nome: 'Emparelha 3 cores',
    faixaEtaria: '2 a 3',
    portage: 'Cognição',
  },
  {
    id: 35,
    nome: 'Coloca objetos dentro, em cima e em baixo de um recipiente, dada a ordem',
    faixaEtaria: '2 a 3',
    portage: 'Cognição',
  },
  {
    id: 36,
    nome: 'Nomeia objetos quando ouve o barulho que fazem',
    faixaEtaria: '2 a 3',
    portage: 'Cognição',
  },
  {
    id: 37,
    nome: 'Monta um brinquedo de encaixe de 4 peças',
    faixaEtaria: '2 a 3',
    portage: 'Cognição',
  },
  {
    id: 38,
    nome: "Nomeia ações em figuras ('O que... está fazendo?')",
    faixaEtaria: '2 a 3',
    portage: 'Cognição',
  },
  {
    id: 39,
    nome: 'Emparelha forma geométrica com a figura da mesma',
    faixaEtaria: '2 a 3',
    portage: 'Cognição',
  },
  {
    id: 40,
    nome: 'Empilha 5 ou mais argolas em uma vara na ordem',
    faixaEtaria: '2 a 3',
    portage: 'Cognição',
  },
  {
    id: 41,
    nome: 'Nomeia objetos como sendo grandes ou pequenos',
    faixaEtaria: '3 a 4',
    portage: 'Cognição',
  },
  {
    id: 42,
    nome: 'Aponta para 10 partes do corpo quando requisitado',
    faixaEtaria: '3 a 4',
    portage: 'Cognição',
  },
  {
    id: 43,
    nome: 'Aponta para menino e menina, dada a ordem',
    faixaEtaria: '3 a 4',
    portage: 'Cognição',
  },
  {
    id: 44,
    nome: 'Diz se um objeto é pesado ou leve',
    faixaEtaria: '3 a 4',
    portage: 'Cognição',
  },
  {
    id: 45,
    nome: 'Une 2 partes de uma figura para formar o todo',
    faixaEtaria: '3 a 4',
    portage: 'Cognição',
  },
  {
    id: 46,
    nome: 'Descreve 2 eventos ou personagens de uma estória familiar ou programa de televisão',
    faixaEtaria: '3 a 4',
    portage: 'Cognição',
  },
  {
    id: 47,
    nome: 'Repete Brincadeiras (rimas ou canções) que envolvam movimentos coordenados',
    faixaEtaria: '3 a 4',
    portage: 'Cognição',
  },
  {
    id: 48,
    nome: 'Emparelha 3 ou mais objetos',
    faixaEtaria: '3 a 4',
    portage: 'Cognição',
  },
  {
    id: 49,
    nome: 'Aponta para objetos compridos ou curtos',
    faixaEtaria: '3 a 4',
    portage: 'Cognição',
  },
  {
    id: 50,
    nome: 'Associa objetos correspondentes. Ex: meia/sapato',
    faixaEtaria: '3 a 4',
    portage: 'Cognição',
  },
  {
    id: 51,
    nome: 'Conta até 3 imitando um adulto',
    faixaEtaria: '3 a 4',
    portage: 'Cognição',
  },
  {
    id: 52,
    nome: 'Agrupa objetos em categorias',
    faixaEtaria: '3 a 4',
    portage: 'Cognição',
  },
  {
    id: 53,
    nome: 'Traça um (V) em imitação',
    faixaEtaria: '3 a 4',
    portage: 'Cognição',
  },
  {
    id: 54,
    nome: 'Traça uma linha diagonal dado o exemplo',
    faixaEtaria: '3 a 4',
    portage: 'Cognição',
  },
  {
    id: 55,
    nome: 'Conta 10 objetos, imitando um adulto',
    faixaEtaria: '3 a 4',
    portage: 'Cognição',
  },
  {
    id: 56,
    nome: 'Constrói uma ponte com 3 blocos por imitação',
    faixaEtaria: '3 a 4',
    portage: 'Cognição',
  },
  {
    id: 57,
    nome: 'Emparelha uma sequência ou padrão (tamanho, cor) de blocos ou contas',
    faixaEtaria: '3 a 4',
    portage: 'Cognição',
  },
  {
    id: 58,
    nome: 'Copia uma séria de (V) interligados',
    faixaEtaria: '3 a 4',
    portage: 'Cognição',
  },
  {
    id: 59,
    nome: 'Acrescenta perna ou braço em um desenho incompleto da figura humana',
    faixaEtaria: '3 a 4',
    portage: 'Cognição',
  },
  {
    id: 60,
    nome: 'Completa um quebra cabeças de 6 peças',
    faixaEtaria: '3 a 4',
    portage: 'Cognição',
  },
  {
    id: 61,
    nome: 'Indica se os objetos são iguais ou diferentes',
    faixaEtaria: '3 a 4',
    portage: 'Cognição',
  },
  {
    id: 62,
    nome: 'Desenha um quadrado imitando um adulto',
    faixaEtaria: '3 a 4',
    portage: 'Cognição',
  },
  {
    id: 63,
    nome: 'Nomeia 3 cores sendo requisitado',
    faixaEtaria: '3 a 4',
    portage: 'Cognição',
  },
  {
    id: 64,
    nome: 'Nomeia 3 formas geométricas (quadrado, triângulo e círculo)',
    faixaEtaria: '3 a 4',
    portage: 'Cognição',
  },
  {
    id: 65,
    nome: 'Apanha de 1 a 5 objetos quando solicitado',
    faixaEtaria: '4 a 5',
    portage: 'Cognição',
  },
  {
    id: 66,
    nome: 'Nomeia 5 texturas diferentes',
    faixaEtaria: '4 a 5',
    portage: 'Cognição',
  },
  {
    id: 67,
    nome: 'Copia um triângulo ao ser requisitado',
    faixaEtaria: '4 a 5',
    portage: 'Cognição',
  },
  {
    id: 68,
    nome: 'Recorda-se de 4 objetos que haviam sido vistos em uma figura',
    faixaEtaria: '4 a 5',
    portage: 'Cognição',
  },
  {
    id: 69,
    nome: 'Diz o momento do dia associado a cada atividades',
    faixaEtaria: '4 a 5',
    portage: 'Cognição',
  },
  {
    id: 70,
    nome: 'Repete rimas familiares',
    faixaEtaria: '4 a 5',
    portage: 'Cognição',
  },
  {
    id: 71,
    nome: 'Diz se um objeto é mais pesado ou mais leve (objetos com diferença de 0,5 quilo)',
    faixaEtaria: '4 a 5',
    portage: 'Cognição',
  },
  {
    id: 72,
    nome: 'Diz o que está faltando quando um objeto é retirado de um grupo de 3 objetos',
    faixaEtaria: '4 a 5',
    portage: 'Cognição',
  },
  {
    id: 73,
    nome: "'portage' Cognição 73’, nomeia 8 cores",
    faixaEtaria: '4 a 5',
    portage: 'Cognição',
  },
  {
    id: 74,
    nome: 'Identifica o valor de 3 moedas',
    faixaEtaria: '4 a 5',
    portage: 'Cognição',
  },
  {
    id: 75,
    nome: 'Espelha símbolos (letras e números)',
    faixaEtaria: '4 a 5',
    portage: 'Cognição',
  },
  {
    id: 76,
    nome: 'Diz a cor de objetos nomeados',
    faixaEtaria: '4 a 5',
    portage: 'Cognição',
  },
  {
    id: 77,
    nome: 'Relata 5 principais fatos de uma história contada 3x',
    faixaEtaria: '4 a 5',
    portage: 'Cognição',
  },
  {
    id: 78,
    nome: 'Desenha figura humana (cabeça, tronco e 4 membros)',
    faixaEtaria: '4 a 5',
    portage: 'Cognição',
  },
  {
    id: 79,
    nome: 'Canta 5 estrofes de uma canção',
    faixaEtaria: '4 a 5',
    portage: 'Cognição',
  },
  {
    id: 80,
    nome: 'Constrói uma pirâmide de 10 blocos por imitação',
    faixaEtaria: '4 a 5',
    portage: 'Cognição',
  },
  {
    id: 81,
    nome: 'Nomeia objetos como sendo compridos ou curtos',
    faixaEtaria: '4 a 5',
    portage: 'Cognição',
  },
  {
    id: 82,
    nome: "Coloca objetos 'atrás', 'ao lado' ou 'junto' a outros",
    faixaEtaria: '4 a 5',
    portage: 'Cognição',
  },
  {
    id: 83,
    nome: 'Faz conjuntos iguais de 10 objetos, segundo modelo',
    faixaEtaria: '4 a 5',
    portage: 'Cognição',
  },
  {
    id: 84,
    nome: 'Nomeia ou aponta para a parte ausente da figura',
    faixaEtaria: '4 a 5',
    portage: 'Cognição',
  },
  {
    id: 85,
    nome: 'Conta de 1 a 20',
    faixaEtaria: '4 a 5',
    portage: 'Cognição',
  },
  {
    id: 86,
    nome: 'Identifica o objeto que está colocado no meio, em primeiro e em último lugar',
    faixaEtaria: '4 a 5',
    portage: 'Cognição',
  },
  {
    id: 87,
    nome: "Contar até 20 objetos e responde adequadamente à pergunta: 'Quantos ... você contou ?'",
    faixaEtaria: '5 a 6',
    portage: 'Cognição',
  },
  {
    id: 88,
    nome: 'Nomeia 10 numerais',
    faixaEtaria: '5 a 6',
    portage: 'Cognição',
  },
  {
    id: 89,
    nome: 'Identifica qual a sua esquerda e qual a sua direita',
    faixaEtaria: '5 a 6',
    portage: 'Cognição',
  },
  {
    id: 90,
    nome: 'Diz as vogais em ordem',
    faixaEtaria: '5 a 6',
    portage: 'Cognição',
  },
  {
    id: 91,
    nome: 'Escreve seu nome com letras de forma',
    faixaEtaria: '5 a 6',
    portage: 'Cognição',
  },
  {
    id: 92,
    nome: 'Nomeia 5 letras do alfabeto',
    faixaEtaria: '5 a 6',
    portage: 'Cognição',
  },
  {
    id: 93,
    nome: 'Ordena objetos em sequência de comprimentos e largura',
    faixaEtaria: '5 a 6',
    portage: 'Cognição',
  },
  {
    id: 94,
    nome: 'Nomeia as Letras maiúsculas do alfabeto',
    faixaEtaria: '5 a 6',
    portage: 'Cognição',
  },
  {
    id: 95,
    nome: 'Coloca numerais de 1 a 10 na sequência correta',
    faixaEtaria: '5 a 6',
    portage: 'Cognição',
  },
  {
    id: 96,
    nome: 'Identifica a posição de objetos em 1º, 2º e 3º lugar',
    faixaEtaria: '5 a 6',
    portage: 'Cognição',
  },
  {
    id: 97,
    nome: 'Nomeia as letras minúsculas do alfabeto',
    faixaEtaria: '5 a 6',
    portage: 'Cognição',
  },
  {
    id: 98,
    nome: 'Emparelha letras maiúsculas com minúsculas',
    faixaEtaria: '5 a 6',
    portage: 'Cognição',
  },
  {
    id: 99,
    nome: 'Aponta para numerais de 1 a 25',
    faixaEtaria: '5 a 6',
    portage: 'Cognição',
  },
  {
    id: 100,
    nome: 'Copia um losango',
    faixaEtaria: '5 a 6',
    portage: 'Cognição',
  },
  {
    id: 101,
    nome: 'Completa um labirinto simples',
    faixaEtaria: '5 a 6',
    portage: 'Cognição',
  },
  {
    id: 102,
    nome: 'Diz os dias da semana na ordem',
    faixaEtaria: '5 a 6',
    portage: 'Cognição',
  },
  {
    id: 103,
    nome: 'Soma e subtrai combinações de até três elementos',
    faixaEtaria: '5 a 6',
    portage: 'Cognição',
  },
  {
    id: 104,
    nome: 'Diz o mês e o dia de seu aniversário',
    faixaEtaria: '5 a 6',
    portage: 'Cognição',
  },
  {
    id: 105,
    nome: 'Lê 10 palavras impressas',
    faixaEtaria: '5 a 6',
    portage: 'Cognição',
  },
  {
    id: 106,
    nome: 'Prediz o que vai ocorrer',
    faixaEtaria: '5 a 6',
    portage: 'Cognição',
  },
  {
    id: 107,
    nome: 'Aponta para os objetos inteiros e partidos ao meio',
    faixaEtaria: '5 a 6',
    portage: 'Cognição',
  },
  {
    id: 108,
    nome: 'Conta de memória de 1 a 100 (pedir que para no 40, e continue no 80, caso não erre até o 40)',
    faixaEtaria: '5 a 6',
    portage: 'Cognição',
  },
];

export const PORTAGE_TIPO = [
  {
    id: 1,
    nome: 'Socialização',
  },
  {
    id: 2,
    nome: 'Cognição',
  },
];

export const PORTAGE_FAIXA_ETARIA = [
  {
    id: 1,
    nome: '0 a 1',
  },
  {
    id: 2,
    nome: '1 a 2',
  },
  {
    id: 3,
    nome: '2 a 3',
  },
  {
    id: 4,
    nome: '3 a 4',
  },
  {
    id: 5,
    nome: '4 a 5',
  },
  {
    id: 6,
    nome: '5 a 6',
  },
];

export const TIPO_PROTOCOLO = [
  {
    id: 1,
    nome: 'Portage',
  },
  {
    id: 2,
    nome: 'VB Mapp',
  },
  {
    id: 3,
    nome: 'PEI',
  },
];
