export const PROCEDIMENTO_ENSINO = [
  {
    id: 1,
    nome: 'PROCEDIMENTO DE ENSINO: ENSINO ESTRUTURADO - DTT - TREINO DE TENTATIVAS DISCRETAS',
  },
  {
    id: 2,
    nome: 'PROCEDIMENTO DE ENSINO: TODO O TEMPO DA SESSÃO ATRAVÉS DE ENSINO NATURALISTA',
  },
  {
    id: 3,
    nome: 'PROCEDIMENTO DE ENSINO:  ENSINO ESTRUTURADO - DTT - TREINO DE TENTATIVAS DISCRETAS E  ATRAVÉS DE ENSINO NATURALISTA',
  },
];

export const METAS = [
  {
    id: 1,
    nome: 'PROCEDIMENTO DE ENSINO: ENSINO ESTRUTURADO - DTT - TREINO DE TENTATIVAS DISCRETAS',
  },
  {
    id: 2,
    nome: 'PROCEDIMENTO DE ENSINO: TODO O TEMPO DA SESSÃO ATRAVÉS DE ENSINO NATURALISTA',
  },
  {
    id: 3,
    nome: 'PROCEDIMENTO DE ENSINO:  ENSINO ESTRUTURADO - DTT - TREINO DE TENTATIVAS DISCRETAS E  ATRAVÉS DE ENSINO NATURALISTA',
  },
];
