export const GUIA_AMIL_STATUS = {
  RASCUNHO: 'RASCUNHO',
  PRONTA_PARA_ENVIO: 'PRONTA_PARA_ENVIO',
  AGUARDANDO_LOTE: 'AGUARDANDO_LOTE',
  VALIDANDO: 'VALIDANDO',
  ERRO_VALIDACAO: 'ERRO_VALIDACAO',
  ENVIANDO: 'ENVIANDO',
  ENVIADA: 'ENVIADA',
  EM_PROCESSAMENTO: 'EM_PROCESSAMENTO',
  PROCESSADA: 'PROCESSADA',
  PROCESSADA_COM_GLOSA: 'PROCESSADA_COM_GLOSA',
  REJEITADA: 'REJEITADA',
  ERRO_COMUNICACAO: 'ERRO_COMUNICACAO',
  CANCELADA: 'CANCELADA',
};

export const LOTE_GUIA_STATUS = {
  CRIADO: 'CRIADO',
  VALIDANDO: 'VALIDANDO',
  INVALIDO: 'INVALIDO',
  ENVIANDO: 'ENVIANDO',
  RECEBIDO: 'RECEBIDO',
  COM_PROTOCOLO: 'COM_PROTOCOLO',
  EM_PROCESSAMENTO: 'EM_PROCESSAMENTO',
  PROCESSADO: 'PROCESSADO',
  PROCESSADO_COM_ERRO: 'PROCESSADO_COM_ERRO',
  REJEITADO: 'REJEITADO',
  ERRO_COMUNICACAO: 'ERRO_COMUNICACAO',
};
